name: .NET

on:
  push:
    branches: [ "dependabot/nuget/BlogEngine/BlogEngine.NET/Moment.js-2.29.2" ]
  pull_request:
    branches: [ "dependabot/nuget/BlogEngine/BlogEngine.NET/Moment.js-2.29.2" ]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1    
    - name: Restore dependencies
      run: nuget restore BlogEngine.sln
    - name: Clean Default Build
      run: msbuild BlogEngine.sln /t:clean
    - name: Build - was dotnet build --no-restore
      run: msbuild.exe BlogEngine.sln /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=./.. /p:DebugSymbols=true /t:build

    - name: List files in the repository and copy artifact
      run: |
          dir ${{ github.workspace }}
          mkdir -p ${{ github.workspace }}/artifact
          copy blog.zip ${{ github.workspace }}/artifact
 
    - name: Check out main branch
      uses: actions/checkout@v2
      with:
        path: ${{ github.workspace }}/artifact
    -  run: |
         echo "Downloading the latest version of the Veracode Java API"
         $versionstring = curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/maven-metadata.xml | findstr /r "latest";
         $version  = $versionstring.Trim() -replace '<latest>','' -replace '</latest>','';
         curl https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/$version/vosp-api-wrappers-java-$version-dist.zip -o dist.zip
         7z e dist.zip -y
         dir D:/a/verademo-dotnet/verademo-dotnet/
         java -jar VeracodeJavaAPI.jar -action uploadandscan -vid '${{ secrets.VERACODE_API_ID }}' -vkey '${{ secrets.VERACODE_API_KEY }}' -appname '${{ secrets.VERACODE_APP_NAME }}' -createprofile true -criticality VeryHigh -sandboxname nightmareBuild -createsandbox true -version Verademo-dotnet-GHA -filepath 'blog.zip' -debug
